### ISSUE TITLE
deploying to username.github.io rather than username.github.io/repo-name/

### ISSUE THREAD

**Issue by bernardino-www** [gregrickaby/nextjs-github-pages#10]
how would you go about deploying to `username.github.io` rather than `username.github.io/repo-name/`? edit the `assetPrefix` value in `nexts.config.js`?

**Comment by TusharShahi** [comment]
Looking for a way to do this

**Comment by Fi1osof** [comment]
Just replace ["/nextjs-github-pages/"](https://github.com/gregrickaby/nextjs-github-pages/blob/main/next.config.js#L8) with "./"
