### ISSUE TITLE
Error when running `npm i` in deploy.yml action

### ISSUE THREAD

**Issue by altosaar** [gregrickaby/nextjs-github-pages#31]
Hi Greg, thanks so much for this!! As a nonprofit we cannot afford Vercel so this is our only option :)

Here is the error we're seeing when we run the script via github actions following https://gregrickaby.blog/article/nextjs-github-pages:

```
Run npm install
added 27 packages, and audited 28 packages in 4s
2 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
> build
> next build
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
info  - Checking validity of types...
Failed to compile.
./components/CodeBlock.tsx:10:22
Type error: Cannot find name 'Prism'.
  8 | 
  9 | React.useEffect(() => {
> 10 | if (ref.current) Prism.highlightElement(ref.current,false);
    | ^
 11 |   }, [children]);
 12 | 
 13 | return (
Error: Process completed with exit code 1.
```

Any ideas how to debug?

Here's the script: https://github.com/onefact/handbook.onefact.org/blob/main/.github/workflows/deploy.yml

Thanks again!!!

**Comment by altosaar** [comment]
cc @benguz

**Comment by gregrickaby** [comment]
@altosaar 👋🏻 Hello there!

Looks like your codebase is trying to use a package ([PrismJS](https://www.npmjs.com/package/prismjs)) which hasn't been installed. Make sure the developer has run `npm i prismjs` and that the `package.json` and `package.lock` files are checked into version control.

I'm glad this has helped your org!
