### ISSUE TITLE
How to serve optimized images?

### ISSUE THREAD

**Issue by altosaar** [gregrickaby/nextjs-github-pages#46]
Super helpful!! Thank you :)

Any idea how we might be able to get images working? 

I’ve been trying to get the static import working (https://nextjs.org/docs/basic-features/image-optimization) on GitHub pages, and can’t figure out how to debug (for onefact.org and Payless.health)

Thank you again!

**Comment by gregrickaby** [comment]
@altosaar Hey there 👋🏻

The short answer is: You can't. See: https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features 

The long answer is: You'd need to use a third-party loader, like Cloudinary to do image optimization when using `next export`.

Hope this helps!

**Comment by altosaar** [comment]
Super helpful thank you @gregrickaby ! I hope they fix this soon.

**Comment by gregrickaby** [comment]
Happy to help. Good luck!
