### ISSUE TITLE
Stuck on keygen commands

### ISSUE THREAD

**Issue by NoahC2022** [gregrickaby/nextjs-github-pages#53]
Great work on the tutorial!

When running the line you gave with the keygen, the terminal said there were too many commands. So, breaking it down, I was able to get the keygen done but -t rsa returns this error message:

"-t : The term '-t' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the     
path is correct and try again.
At line:1 char:1
+ -t rsa -b 4096 -C "$(git config user.email)" -f gh-pages -N ""
+ ~~
    + CategoryInfo          : ObjectNotFound: (-t:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException "
    
I don't fully understand all the steps happening here, so it's tough to try and debug or find a workaround. If you have Discord and want to chat about it, let me know!

**Comment by gregrickaby** [comment]
@NoahC2022 I just updated this repo to support the new App Router and Github's new [pages workflow](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/) which no longer requires the use of SSH keys. 

Would you mind trying it out and to see if your app deploys? 😄
