### ISSUE TITLE
The deployment scheme has changed for Next 14

### ISSUE THREAD

**Issue by GlebShulga** [gregrickaby/nextjs-github-pages#56]
output: "export" is deprecated. It doesn't work anymore.

**Comment by gregrickaby** [comment]
@GlebShulga I see that under [Version History](https://nextjs.org/docs/app/building-your-application/deploying/static-exports#version-history). I believe they're talking about the CLI command `next export`. 

I updated this example to the latest from `create-next-app` this morning, and all the [deployments worked](https://github.com/gregrickaby/nextjs-github-pages/actions). I also don't see anything that would indicate exporting is deprecated in the [official docs](https://nextjs.org/docs/app/building-your-application/deploying/static-exports).
