### ISSUE TITLE
Statci export in github pages does not work with dynamic

### ISSUE THREAD

**Issue by abolfazlcodes** [gregrickaby/nextjs-github-pages#62]
Imagine having an `articles` page which has a single article as well which is dynamic `[slug].tsx`. During the build process, it throws this error:

> Build error occurred
> Error: Page "/articles/[slug]" is missing "generateStaticParams()" so it cannot be used with the "output: export" config.

How should we handle this situation. It is app router not page router to use `generateStaticParams()`

**Comment by gregrickaby** [comment]
Hey @abolfazlcodes, dynamic features are not supported with static exports: https://nextjs.org/docs/app/building-your-application/deploying/static-exports#unsupported-features
